from django.conf import settings
import json
import os
import pickle
import re
from django.http import FileResponse, Http404

from mlserver.safe_ml import ModelBundleError, save_signed_model_bundle
from mlserver.task_access import require_task_access


SAFE_ARTIFACT_NAME = re.compile(r'^[A-Za-z0-9][A-Za-z0-9_. -]{0,199}$')


def _json_safe(value):
    """Convert numpy-like scalar metadata to values accepted by JSON."""
    try:
        json.dumps(value)
        return value
    except (TypeError, ValueError):
        if isinstance(value, dict):
            return {str(key): _json_safe(item) for key, item in value.items()}
        if isinstance(value, (list, tuple)):
            return [_json_safe(item) for item in value]
        if hasattr(value, 'item'):
            return value.item()
        return str(value)


def _task_from_method(method):
    mapping = {
        'model_bclass': 'binary_classification',
        'model_mclass': 'multiclass_classification',
        'model_reg': 'regression',
        'model_sur': 'survival',
    }
    return mapping.get(method)


def _write_bundle_from_legacy(legacy_path, bundle_path, default_name):
    if not settings.MALER_MODEL_SIGNING_KEY:
        raise ModelBundleError(
            'MALER_MODEL_SIGNING_KEY must be configured before model download.')
    # These pickle files are generated by MALER or shipped as trusted examples.
    # User-uploaded pickle artifacts are never passed to this helper.
    with open(legacy_path, 'rb') as handle:
        model_info = pickle.load(handle)
    task = _task_from_method(model_info.get('method'))
    if task is None:
        raise ModelBundleError('Unsupported cached model task.')
    trained_model = model_info['model']
    if task == 'survival' and model_info.get('ytrain') is not None:
        trained_model.maler_ytrain_ = model_info['ytrain']
    metadata = {
        'method': model_info.get('method'),
        'model_name': model_info.get('name', default_name),
        'classes': _json_safe(model_info.get('classes')),
        'legacy_preprocessing': model_info.get('scaler'),
        'pipeline_complete': False,
    }
    save_signed_model_bundle(
        bundle_path,
        trained_model,
        task,
        model_info['feature_names'],
        settings.MALER_MODEL_SIGNING_KEY,
        metadata=metadata,
    )

def download_sample_data(request, fname):
    if not SAFE_ARTIFACT_NAME.fullmatch(fname) or os.path.basename(fname) != fname:
        raise Http404
    file_path = os.path.join(settings.STATIC_ROOT, 'cache', 'example', fname)
    try:
        if fname.lower().endswith('.maler') and not os.path.exists(file_path):
            legacy_path = os.path.splitext(file_path)[0] + '.pkl'
            _write_bundle_from_legacy(
                legacy_path, file_path, os.path.splitext(fname)[0])
        response = FileResponse(open(file_path, 'rb'), content_type='application/octet-stream')
        response['Content-Disposition'] = 'attachment; filename="%s"' % fname
        return response
    except (OSError, KeyError, pickle.UnpicklingError, ModelBundleError):
        raise Http404


def download_model(request, projectid_model):
    parts = projectid_model.split('_', 1)
    if len(parts) != 2:
        raise Http404
    projectid, model = parts[0], parts[1].replace(' ', '_')
    if (not SAFE_ARTIFACT_NAME.fullmatch(projectid) or
            not SAFE_ARTIFACT_NAME.fullmatch(model) or
            os.path.basename(projectid) != projectid or
            os.path.basename(model) != model):
        raise Http404

    # Direct function calls are retained for the trusted conversion test and
    # internal tooling. Every HTTP download requires the task capability token.
    if request is not None:
        require_task_access(request, projectid)

    cache_dir = os.path.join(settings.STATIC_ROOT, 'cache', projectid)
    legacy_path = os.path.join(cache_dir, model + '.pkl')
    bundle_path = os.path.join(cache_dir, model + '.maler')
    try:
        if not os.path.exists(bundle_path):
            _write_bundle_from_legacy(legacy_path, bundle_path, model)
        response = FileResponse(open(bundle_path, 'rb'), content_type='application/octet-stream')
        response['Content-Disposition'] = (
            'attachment; filename="%s"' % (projectid + '_' + model + '.maler'))
        return response
    except (OSError, KeyError, pickle.UnpicklingError, ModelBundleError):
        raise Http404


#
# def cp_download_model(request, projectid_model):
#     projectid = projectid_model.split('_')[0]
#     # model = projectid_model.split('_')[1].replace(' ','_')
#     md5 = ''
#     file_path = (STATIC_ROOT + '/cache/' + projectid + '/' + md5 + '.pkl')
#     try:
#         response = StreamingHttpResponse(open(file_path, 'rb'))
#         response['content_type'] = "application/octet-stream"
#         response['Content-Disposition'] = 'attachment; filename=' + projectid + '_' + os.path.basename(file_path)
#         return response
#     except Exception:
#         raise Http404
