"""
Django settings for ML_WebServer project.

Generated by 'django-admin startproject' using Django 2.1.8.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import sys



# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'change-me-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get(
    'DJANGO_DEBUG', 'True' if 'runserver' in sys.argv else 'False'
).lower() == 'true'
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        'DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost,www.inbirg.com'
    ).split(',')
    if host.strip()
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # mlserver
    'mlserver.apps.MlserverConfig',
    #websocket
    'dwebsocket',

]

# Gunicorn/uWSGI is a Linux process manager, not a Django application.  It is
# intentionally absent from INSTALLED_APPS and from the Windows test environment.

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'mlserver.middleware.ProjectIdentifierMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = os.environ.get('DJANGO_SECURE_SSL', 'False').lower() == 'true'
CSRF_COOKIE_SECURE = os.environ.get('DJANGO_SECURE_SSL', 'False').lower() == 'true'
SECURE_SSL_REDIRECT = os.environ.get('DJANGO_SECURE_SSL', 'False').lower() == 'true'
SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_SECONDS > 0
SECURE_HSTS_PRELOAD = SECURE_HSTS_SECONDS > 0
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]

# Upload and model-artifact limits.  Nginx/reverse-proxy limits must be set to
# the same or smaller values in production.
MALER_MAX_DATA_UPLOAD_BYTES = int(os.environ.get('MALER_MAX_DATA_UPLOAD_BYTES', 200 * 1024 * 1024))
MALER_MAX_MODEL_UPLOAD_BYTES = int(os.environ.get('MALER_MAX_MODEL_UPLOAD_BYTES', 100 * 1024 * 1024))
DATA_UPLOAD_MAX_MEMORY_SIZE = MALER_MAX_DATA_UPLOAD_BYTES
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get('MALER_FILE_MEMORY_LIMIT_BYTES', 5 * 1024 * 1024))
MALER_MODEL_SIGNING_KEY = os.environ.get('MALER_MODEL_SIGNING_KEY', '')
MALER_ALLOW_LEGACY_MODEL_UPLOAD = False
MALER_CACHE_RETENTION_HOURS = int(os.environ.get('MALER_CACHE_RETENTION_HOURS', '24'))
MALER_WEB_OUTER_SPLITS = int(os.environ.get('MALER_WEB_OUTER_SPLITS', '5'))
MALER_WEB_OUTER_REPEATS = int(os.environ.get('MALER_WEB_OUTER_REPEATS', '2'))
MALER_WEB_INNER_SPLITS = int(os.environ.get('MALER_WEB_INNER_SPLITS', '3'))
MALER_WEB_N_JOBS = int(os.environ.get('MALER_WEB_N_JOBS', '1'))
# Historical websocket endpoints bypassed fold-local preprocessing and are kept
# disabled.  All public result URLs now use the validated nested-CV service.
MALER_ENABLE_LEGACY_EXPLORATORY = False

ROOT_URLCONF = 'ML_WebServer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ML_WebServer.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

# STATIC_URL = '/static/'
STATIC_URL = '/mlserver_static/'
MLSERVER_STATIC_DIR = os.path.join(BASE_DIR, 'mlserver', 'static')
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


#dwebSocket uwsgi
# import dwebsocket
# MIDDLEWARE_CLASSES=['dwebsocket.middleware.WebSocketMiddleware']      # 为所有的URL提供websocket，如果只是单独的视图需要可以不选
# WEBSOCKET_ACCEPT_ALL=True # 可以允许每一个单独的视图使用websockets
# WEBSOCKET_FACTORY_CLASS='dwebsocket.backends.uwsgi.factory.uWsgiWebSocketFactory' #uwsgi

#email
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.163.com'      #163邮箱的邮箱服务地址
EMAIL_PORT = 465  # 端口为465或587
EMAIL_USE_SSL = True  # SSL加密方式设置为True
EMAIL_USE_TLS = False
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
